version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"  # Exposes Redis on port 6379
    networks:
      - backend-network

  backend:
    build: .
    container_name: wallz-backend
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis:6379  # Backend connects to Redis via this URL
    depends_on:
      - redis
    networks:
      - backend-network
    env_file:
      - .env  # Make sure .env is correctly placed and contains required env variables

networks:
  backend-network:
    driver: bridge
